### ISSUE TITLE
segmentation core

### ISSUE THREAD

**Issue by KAITO-FBX** [taviso/loadlibrary#64]
Thank you very much for your package.      

I am currently trying to see what could be done with a win32 dll from a FMU (functional mockup interface file) ... just out of curiosity as people can generate linux64 libraries or even give the sources ... here not the case.     

I have cloned it on my system : 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64  

Got the engine/mpengine.dll    

Not sure I have the libreadline-dev:i386 .... the direct apt instill doesn't work and debian doesn't give me access (it seems to it) ... still trying to get it.     

At this time I have this :    
./mpclient MODELICA_0Demo_testmotor_03.dll 
Segmentation fault

QUESTION : Do you have any suggestion ... my first idea is the :i386 missing install and I am trying to get it .. but does this gdb output gives you any ideas ?
Thank you again 

 gdb ./mpclient 
...This GDB was configured as "x86_64-linux-gnu" ...
(gdb) run
Starting program: ... loadlibrary/mpclient 
Program received signal SIGSEGV, Segmentation fault.
0xf6ba6f5c in ?? ()
(gdb)

**Comment by earada** [comment]
@KAITO-FBX I'm experiencing the same issue on a clean installation. It seems that there was a change in mpengine.dll that breaks loadlibrary.

Last working version: 1.1.15700.9
Current product version: 1.1.15800.1

**Comment by taviso** [comment]
Thank you for letting me know, I see the problem.

There were two problems, `RegisterTraceGuidsW` was incorrectly declared as using cdecl calling convention - this was causing the stack to be misaligned, and then a security check failed. Windows code will sometimes execute `int 0x29` when an error is detected, this is what was happening here.

Secondly, some code changed that used to check the return code of `GetEnvironmentVariable`, but now ignores the return code and checks the value of `GetLastError`. On Windows that would usually be set to `ERROR_ENVVAR_NOT_FOUND` if a variable wasn't set - I never bothered setting it because nobody checked it, but now it needs that.

I'll commit a fix asap.

**Comment by KAITO-FBX** [comment]
Thank you very much

**Comment by worlvlhole** [comment]
Anyone still having issues with the most recent symbols?
No longer getting the segmentation fault but getting this `Aborted (core dumped)`

**Comment by taviso** [comment]
Hmm, seems to be working here on a clean checkout.

Can you give me the file you're trying to scan, and the output of this command:

`$ exiftool mpengine.dll  | grep 'Product Version Number'`

 (FYI, I'm testing with `1.1.15800.1`)

**Comment by worlvlhole** [comment]
Yep, it was my fault. Ran into docker seccomp blocking me. Thanks!

**Comment by KAITO-FBX** [comment]
Hello 
Thank you for your help and answers.
I have pulled the new repo and compiled.
Now here is the result :
-----------------------------------------------------------------------------
/loadlibrary$ ./mpclient MODELICA_0Demo_testmotor_03.dll
main(): Scanning MODELICA_0Demo_testmotor_03.dll...
EngineScanCallback(): Scanning input
------------------------------------------------------------------------------
So not segmentation core. ... I now have to see how to access the dll from a gcc code :-)    
But this is my problem now lol ... (I don't want any RTFM from you )    
Thank you very much
