### ISSUE TITLE
Engine version 1.339.932.0 (2021/05/18) breaks mpclient

### ISSUE THREAD

**Issue by ventulis** [taviso/loadlibrary#98]
The engine version [`1.339.932.0`](https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.339.932.0/x86/mpam-fe.exe) will break mpclient. Last working version is [`1.339.927.0`](https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.339.927.0/x86/mpam-fe.exe).

The broken version will output:

```
$ ./mpclient file.txt
mpclient: function at 0xec01a82d attempted to call an unknown symbol
Trace/breakpoint trap
```

**Comment by taviso** [comment]
Thanks for letting me know, I can see it's using some new APIs like `CompareStringOrdinal()` , that's pretty easy to fix.

It's also doing some weird stuff with the Etw API that I don't understand, but returning -1 from `EtwRegister()` seems to fix it. I'll commit that for now, because working for unknown reasons is better than crashing!

**Comment by ventulis** [comment]
Great! Thanks! :+1:

**Comment by hi3cmz** [comment]
Excuse me, I come across here because of I am using some vintage (circa 2008) pxi (pci) bus instruments that come with self contained dll (.lib) driver and .h, help page for all functions for development on COM, I am thinking to use the dll on python + qt in linux, is thatpossible? what do I need to do to make linux python load those pci driver? thanks!
